version: "3.8"

services:
  db:
    image: mysql:8.1
    container_name: tododb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tododb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: secure-todo-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tododb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - todo-network

volumes:
  mysql-data:

networks:
  todo-network:
